"""确定性 Evidence Rerank（TASK-011 §B，Module/02 §4.5，D-16：V1 内置、无模型、零延迟）。

12 条特征逐项落地（分值为初始值，TASK-015 校准**只改默认值不改特征结构**）：

| 特征 | 分值 | 信号来源 |
|---|---|---|
| Explicit symbol/path 命中 | +2.0 | Exact-Explicit（§4.2-a） |
| query 符号名与 chunk 符号名等值 | +1.0 | Exact-Inferred |
| 3 通道共识 | +0.5 | candidate.channel_ranks |
| 与 top-1 种子图连通（1 跳） | +0.5 | expand 的 ``graph-expanded from`` 记录 |
| doctype ∈ HIGH_VALUE_DOCTYPES | +0.8 | classify_doctype（索引侧同一函数） |
| 入口点 / 被导出符号 | +0.2 | symbols.is_exported + 无内部调用者 |
| generated 文件 | −1.0 | signals.generated_paths（见下） |
| test fixture（非测试意图查询） | −0.5 | candidate.kind=test + 查询意图 |
| stale spec 引用 | −0.8 | spec_references.stale |
| fallback_block | −0.5 | chunks.symbol_kind |
| 图距离 2 跳 | −0.3 | candidate.graph_depth |
| 合成边（provenance=synthesized）扩展 | −0.2 | edges.provenance |

基准分与量级（本卡口径，记录于任务卡"执行记录"）：``score = rrf_score * RRF_BASE_SCALE + Σ特征``。
``rrf_score = Σ 1/(60+rank) ∈ (0, 0.033]``，与特征表（±0.2..2.0）差两个数量级；不缩放的话
特征表实际失效（单个 +2.0 恒压过任何 RRF 差异），Module/02 §4.6 的反例（"Explicit 命中无关 UI
模块 vs 三通道共识的强相关符号 → 共识者胜"）也无法成立。故引入 ``RRF_BASE_SCALE = 100.0``
把基准分换算到与特征可比的量级；特征结构不变，仅一个额外的全局缩放常量。

数据来源缺口（详见任务卡"未决问题"）：``files.generated`` 目前既无 Store 读 API、W1 写入端
也恒写 0，因此 ``is_generated_path`` 用 Module/01 §4.2 的**文件名约定**做临时代理；
``files.generated`` 可读后应切换为读取索引信号（届时本函数只改 ``collect_signals`` 一处）。
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field, replace

from zace_core.parsing.markdown import classify_doctype
from zace_core.retrieval.exact import extract_inferred, parse_explicit
from zace_core.retrieval.expand import GRAPH_REASON_PREFIX, SYNTHESIZED_REASON
from zace_core.retrieval.fusion import (
    KIND_FALLBACK,
    KIND_SPEC,
    KIND_TEST,
    REASON_EXPLICIT_PATH,
    is_test_path,
)
from zace_core.storage import Store
from zace_core.types import Candidate

__all__ = [
    "FEATURE_NAMES",
    "HIGH_VALUE_DOCTYPES",
    "RRF_BASE_SCALE",
    "RerankSignals",
    "RerankWeights",
    "collect_signals",
    "features",
    "is_generated_path",
    "is_test_intent",
    "rerank",
    "with_weights",
]

#: 基准分缩放（见模块 docstring"基准分与量级"）。
RRF_BASE_SCALE = 100.0

#: rerank 加分的 doctype 白名单（D-42 高信息密度文档）。
HIGH_VALUE_DOCTYPES = frozenset({"agent-instructions", "design", "adr", "readme", "api"})

FEATURE_EXPLICIT = "explicit symbol/path hit"
FEATURE_SYMBOL_MATCH = "query symbol == chunk symbol"
FEATURE_CONSENSUS3 = "3-channel consensus"
FEATURE_GRAPH_1HOP = "graph connected to top-1 seed (1 hop)"
FEATURE_DOCTYPE = "high-value doctype"
FEATURE_ENTRY_POINT = "entry point / exported symbol"
FEATURE_GENERATED = "generated file"
FEATURE_TEST_FIXTURE = "test fixture (non-test intent)"
FEATURE_STALE_SPEC = "stale spec reference"
FEATURE_FALLBACK = "fallback_block"
FEATURE_GRAPH_2HOP = "graph distance 2 hops"
FEATURE_SYNTHESIZED = "synthesized edge"

#: 特征名（供测试与 03 的可解释性断言引用）。
FEATURE_NAMES = (
    FEATURE_EXPLICIT,
    FEATURE_SYMBOL_MATCH,
    FEATURE_CONSENSUS3,
    FEATURE_GRAPH_1HOP,
    FEATURE_DOCTYPE,
    FEATURE_ENTRY_POINT,
    FEATURE_GENERATED,
    FEATURE_TEST_FIXTURE,
    FEATURE_STALE_SPEC,
    FEATURE_FALLBACK,
    FEATURE_GRAPH_2HOP,
    FEATURE_SYNTHESIZED,
)

#: "测试意图查询" 的确定性词表（V1 口径，见任务卡"执行记录"）。
_TEST_INTENT_WORDS = (
    "test",
    "tests",
    "pytest",
    "unittest",
    "fixture",
    "测试",
    "单测",
    "用例",
)

_GENERATED_NAME_MARKERS = ("_generated.", "autogen", "autogenerated")
_GENERATED_SUFFIXES = (".pb.cc", ".pb.h", ".pb.cpp", ".pb2.py", ".designer.cs", ".g.cs")


def is_generated_path(path: str) -> bool:
    """generated 文件的**文件名约定**判定（Module/01 §4.2 的 V1 规则）。

    临时代理：``files.generated`` 目前不可读且恒为 0（见模块 docstring 的缺口说明）。
    """
    name = path.replace("\\", "/").rsplit("/", 1)[-1].lower()
    if any(marker in name for marker in _GENERATED_NAME_MARKERS):
        return True
    return any(name.endswith(suffix) for suffix in _GENERATED_SUFFIXES)


def is_test_intent(query: str) -> bool:
    """查询是否带测试意图（V1 确定性规则：命中测试词表）。"""
    lowered = query.lower()
    return any(word in lowered for word in _TEST_INTENT_WORDS)


@dataclass(frozen=True, slots=True)
class RerankWeights:
    """12 条特征的分值（字段与 Module/02 §4.5 特征表一一对应）。"""

    explicit_hit: float = 2.0
    symbol_match: float = 1.0
    consensus3: float = 0.5
    graph_1hop_top1: float = 0.5
    doctype_high_value: float = 0.8
    entry_point: float = 0.2
    generated: float = -1.0
    test_fixture: float = -0.5
    stale_spec_ref: float = -0.8
    fallback_block: float = -0.5
    graph_2hop: float = -0.3
    synthesized_edge: float = -0.2


@dataclass(frozen=True, slots=True)
class RerankSignals:
    """rerank 的候选外信号（由 ``collect_signals`` 从索引与查询收集）。"""

    query_symbols: frozenset[str] = frozenset()
    explicit_chunk_ids: frozenset[str] = frozenset()
    top1_seed_chunk_id: str | None = None
    exported_chunk_ids: frozenset[str] = frozenset()
    generated_paths: frozenset[str] = frozenset()
    stale_chunk_ids: frozenset[str] = frozenset()
    test_intent: bool = False
    doctype_by_chunk: Mapping[str, str] = field(default_factory=dict)


def _symbol_names(symbol: str) -> set[str]:
    """符号的等价拼写集合（``A.b`` / ``A::b`` 视为同一符号）。"""
    normalized = symbol.replace("::", ".")
    return {symbol, normalized, normalized.rsplit(".", 1)[-1], symbol.replace(".", "::")}


def _explicit_hit(candidate: Candidate) -> bool:
    if candidate.tier == 0 and "exact" in candidate.channel_ranks:
        return True
    if "exact" in candidate.channel_ranks:
        return True
    return REASON_EXPLICIT_PATH in candidate.reasons


def _graph_parent(candidate: Candidate) -> str | None:
    for reason in candidate.reasons:
        if reason.startswith(GRAPH_REASON_PREFIX):
            return reason[len(GRAPH_REASON_PREFIX) :]
    return None


def _doctype(candidate: Candidate, signals: RerankSignals) -> str | None:
    known = signals.doctype_by_chunk.get(candidate.chunk_id)
    if known is not None:
        return known
    if candidate.kind == KIND_SPEC and candidate.path:
        return classify_doctype(candidate.path)
    return None


def features(
    candidate: Candidate,
    signals: RerankSignals,
    weights: RerankWeights,
) -> list[tuple[str, float]]:
    """逐条判定 12 个特征，返回命中的 ``(特征名, 分值)`` 列表（未命中不返回）。"""
    hits: list[tuple[str, float]] = []

    def hit(name: str, value: float, condition: bool) -> None:
        if condition and value != 0.0:
            hits.append((name, value))

    hit(FEATURE_EXPLICIT, weights.explicit_hit, _explicit_hit(candidate))

    symbol = candidate.symbol_fqn
    if symbol and signals.query_symbols:
        spellings = _symbol_names(symbol)
        hit(
            FEATURE_SYMBOL_MATCH,
            weights.symbol_match,
            any(spelling in signals.query_symbols for spelling in spellings),
        )

    hit(FEATURE_CONSENSUS3, weights.consensus3, len(candidate.channel_ranks) >= 3)

    parent = _graph_parent(candidate)
    hit(
        FEATURE_GRAPH_1HOP,
        weights.graph_1hop_top1,
        parent is not None
        and candidate.graph_depth == 1
        and signals.top1_seed_chunk_id is not None
        and parent == signals.top1_seed_chunk_id,
    )

    doctype = _doctype(candidate, signals)
    hit(
        FEATURE_DOCTYPE,
        weights.doctype_high_value,
        doctype in HIGH_VALUE_DOCTYPES if doctype is not None else False,
    )
    hit(FEATURE_ENTRY_POINT, weights.entry_point, candidate.chunk_id in signals.exported_chunk_ids)
    hit(
        FEATURE_GENERATED,
        weights.generated,
        bool(candidate.path) and candidate.path in signals.generated_paths,
    )
    hit(
        FEATURE_TEST_FIXTURE,
        weights.test_fixture,
        candidate.kind == KIND_TEST and not signals.test_intent,
    )
    hit(FEATURE_STALE_SPEC, weights.stale_spec_ref, candidate.chunk_id in signals.stale_chunk_ids)
    hit(FEATURE_FALLBACK, weights.fallback_block, candidate.kind == KIND_FALLBACK)
    hit(FEATURE_GRAPH_2HOP, weights.graph_2hop, candidate.graph_depth >= 2)
    hit(FEATURE_SYNTHESIZED, weights.synthesized_edge, SYNTHESIZED_REASON in candidate.reasons)
    return hits


def rerank(
    candidates: Sequence[Candidate],
    signals: RerankSignals | None = None,
    weights: RerankWeights | None = None,
) -> list[Candidate]:
    """就地写入 ``score`` 并按最终分降序返回（``rrf_score`` 保持不变）。

    命中特征以 ``"<特征名> <分值>"`` 追加进 ``reasons``（可解释性，进 ContextPack reason）。
    ``candidates`` 为 ``Candidate``（非 frozen）→ 直接更新并返回同一批对象。
    """
    active_signals = signals or RerankSignals()
    active_weights = weights or RerankWeights()
    for candidate in candidates:
        base = candidate.rrf_score * RRF_BASE_SCALE
        hits = features(candidate, active_signals, active_weights)
        candidate.score = base + sum(value for _name, value in hits)
        for name, value in hits:
            reason = f"{name} {value:+.1f}"
            if reason not in candidate.reasons:
                candidate.reasons.append(reason)
    return sorted(candidates, key=lambda c: (-c.score, -c.rrf_score, c.chunk_id))


# --------------------------------------------------------------------------- 信号收集


def collect_signals(
    store: Store,
    query: str,
    candidates: Sequence[Candidate],
    *,
    test_intent: bool | None = None,
    generated_paths: Iterable[str] | None = None,
    doctype_by_chunk: Mapping[str, str] | None = None,
) -> RerankSignals:
    """从索引 + 查询收集 rerank 需要的候选外信号。

    可显式覆盖 ``test_intent`` / ``generated_paths`` / ``doctype_by_chunk``（TASK-013 装配与
    测试用）；``generated_paths=None`` 时用 :func:`is_generated_path` 的文件名约定代理。
    """
    explicit = parse_explicit(query)
    query_symbols = frozenset(explicit.symbols) | frozenset(extract_inferred(query))

    explicit_chunk_ids = frozenset(c.chunk_id for c in candidates if _explicit_hit(c))
    ordered = sorted(candidates, key=lambda c: (-c.score, -c.rrf_score, c.chunk_id))
    top1 = ordered[0].chunk_id if ordered else None

    entry_points = _exported_chunk_ids(store, candidates)
    stale_chunks = _stale_spec_chunk_ids(store, candidates)

    if generated_paths is None:
        generated = frozenset(c.path for c in candidates if c.path and is_generated_path(c.path))
    else:
        generated = frozenset(generated_paths)

    if test_intent is None:
        test_intent = is_test_intent(query) or _query_names_test_symbol(store, query_symbols)

    doctypes = (
        dict(doctype_by_chunk)
        if doctype_by_chunk is not None
        else {
            c.chunk_id: classify_doctype(c.path)
            for c in candidates
            if c.kind == KIND_SPEC and c.path
        }
    )

    return RerankSignals(
        query_symbols=query_symbols,
        explicit_chunk_ids=explicit_chunk_ids,
        top1_seed_chunk_id=top1,
        exported_chunk_ids=entry_points,
        generated_paths=generated,
        stale_chunk_ids=stale_chunks,
        test_intent=test_intent,
        doctype_by_chunk=doctypes,
    )


def _exported_chunk_ids(store: Store, candidates: Sequence[Candidate]) -> frozenset[str]:
    """被导出符号的 chunk（+0.2，信号源 = ``symbols.is_exported``，Module/02 §4.5）。

    "入口点 = 无内部调用者且 is_exported" 是 is_exported 的子集，二者并集仍是 is_exported；
    入口点判定的另一用处在 ``expand`` 的 caller 爆炸截断排序（那里才需要 edges 信号）。
    """
    found: set[str] = set()
    for candidate in candidates:
        fqn = candidate.symbol_fqn
        if not fqn:
            continue
        if any(row.fqn == fqn and row.is_exported for row in store.exact_symbols(fqn, limit=None)):
            found.add(candidate.chunk_id)
    return frozenset(found)


def _stale_spec_chunk_ids(store: Store, candidates: Sequence[Candidate]) -> frozenset[str]:
    """带 stale 引用的 SpecBlock chunk（−0.8，G4 的 rerank 侧消费）。"""
    found: set[str] = set()
    for candidate in candidates:
        if candidate.kind != KIND_SPEC:
            continue
        if any(ref.stale for ref in store.spec_refs_for_spec(candidate.chunk_id)):
            found.add(candidate.chunk_id)
    return frozenset(found)


def _query_names_test_symbol(store: Store, query_symbols: frozenset[str]) -> bool:
    """“路由为 General 且查询符号命中 tests/ 路径” 的确定性判定（V1 第二条件）。"""
    for symbol in query_symbols:
        for row in store.exact_symbols(symbol, limit=None):
            if row.file_path and is_test_path(row.file_path):
                return True
    return False


def with_weights(weights: RerankWeights, **overrides: float) -> RerankWeights:
    """按字段名覆盖权重（TASK-015 校准入口；未知字段直接报错）。"""
    return replace(weights, **overrides)
