"""generated 文件判定（Module/01 §4.2 / §6 待决项 2）。

**为什么单独成模块**：判定要同时被**索引期**（写 ``files.generated`` 列）与**检索期**
（``rerank`` 读候选批量信号）使用。放在 ``retrieval.rerank`` 里会让索引流水线反向依赖
检索层；放在这里则两侧都只依赖 ``pipeline``（core 内部的低层包）。

规则（设计文档 §455 定的 V1 口径）：

1. **文件名约定**：``*_generated.*`` / ``*autogen*`` / ``*.pb.cc`` / ``*.pb.h`` /
   ``*.pb.cpp`` / ``*.pb2.py`` / ``*.designer.cs`` / ``*.g.cs``；
2. **内容 banner**：文件头部若干行里的典型生成器标记（``DO NOT EDIT``、
   ``Generated by``、``@generated`` 等）——补足"命名不符合约定但确实是生成的"文件。

误判代价不对称：把手写文件当 generated 会**降权真实证据**，因此内容检测只看**文件头部**
（生成 banner 一定在顶部），不做全文搜索；关键词也只用强标记（见 ``GENERATED_BANNER_MARKERS``）。
实测：加上裸 ``"generated by"`` 会把 leveldb 的 ``table/block.cc``（注释里提到 "blocks
生成 by block_builder.cc"）误判为生成文件。
"""

from __future__ import annotations

__all__ = [
    "GENERATED_BANNER_SCAN_LINES",
    "is_generated",
    "is_generated_content",
    "is_generated_path",
]

#: 文件名约定标记（小写匹配，命中即视为生成文件）。
GENERATED_NAME_MARKERS = ("_generated.", "autogen", "autogenerated")

#: 文件名后缀约定（小写匹配）。
GENERATED_SUFFIXES = (
    ".pb.cc",
    ".pb.h",
    ".pb.cpp",
    ".pb2.py",
    ".designer.cs",
    ".g.cs",
)

#: 内容 banner 关键词（小写匹配）。
#:
#: **刻意保守**：只放不会在自然语言注释里偶然出现的整句。
#: 反例（实测误报，勿加回）：裸 ``"generated by"`` 会命中 leveldb ``table/block.cc`` 的注释
#: "Decodes the blocks generated by block_builder.cc"——那是**核心手写文件**，误降权会伤害
#: 真实证据。需要表达“由代码生成器产出”时必须带上限定词（``code generated by`` 等）。
GENERATED_BANNER_MARKERS = (
    "do not edit",
    "don't edit",
    "@generated",
    "auto-generated",
    "autogenerated by",
    "this file was generated",
    "machine generated",
    "code generated by",
    "automatically generated",
)

#: 内容 banner 只扫文件头部这么多行（banner 必在顶部；全文扫描会误伤引用这些词的文档）。
GENERATED_BANNER_SCAN_LINES = 10


def is_generated_path(path: str) -> bool:
    """按**文件名约定**判定生成文件（Module/01 §4.2 的 V1 规则）。"""
    name = path.replace("\\", "/").rsplit("/", 1)[-1].lower()
    if any(marker in name for marker in GENERATED_NAME_MARKERS):
        return True
    return any(name.endswith(suffix) for suffix in GENERATED_SUFFIXES)


def is_generated_content(text: str) -> bool:
    """按**内容 banner** 判定生成文件（只看头部 ``GENERATED_BANNER_SCAN_LINES`` 行）。

    与 :func:`is_generated_path` 是"或"关系：任一命中即算生成文件。
    """
    head = text.split("\n", GENERATED_BANNER_SCAN_LINES)[:GENERATED_BANNER_SCAN_LINES]
    lowered = "\n".join(head).lower()
    return any(marker in lowered for marker in GENERATED_BANNER_MARKERS)


def is_generated(path: str, text: str | None = None) -> bool:
    """文件级生成判定：文件名约定 **或** 内容 banner（``text=None`` 时只看文件名）。"""
    if is_generated_path(path):
        return True
    return text is not None and is_generated_content(text)

